<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DR_Bahig_Books_Portal_Setup</AssemblyName>
    <ApplicationIcon>..\BookShopPrintAgent\book.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\BookShopPrintAgent\publish\BookShopPrintAgent.exe" LogicalName="BookShopPrintAgent.exe" />
    <EmbeddedResource Include="..\BookShopPrintAgent\publish\appsettings.json" LogicalName="appsettings.json" />
  </ItemGroup>

</Project>
